/**
 * Maps App Store Connect resource roots onto the domains we expose as
 * filterable tool groups. Anything unmapped falls through to `misc`.
 *
 * Grouping is by what a person is trying to get done, not by Apple's URL
 * hierarchy — "ship a release" touches appStoreVersions, appStoreReviewDetails
 * and appStoreVersionSubmissions, so those live together.
 */
export const DOMAIN_MAP: Record<string, string> = {
  // Apps and metadata
  apps: 'apps',
  appInfos: 'apps',
  appInfoLocalizations: 'apps',
  appCategories: 'apps',
  appAvailabilities: 'apps',
  appEncryptionDeclarations: 'apps',
  appEncryptionDeclarationDocuments: 'apps',
  endUserLicenseAgreements: 'apps',
  territories: 'apps',
  territoryAvailabilities: 'apps',
  ageRatingDeclarations: 'apps',
  accessibilityDeclarations: 'apps',
  marketplaceSearchDetails: 'apps',
  alternativeDistributionPackages: 'apps',
  alternativeDistributionPackageDeltas: 'apps',
  alternativeDistributionPackageVariants: 'apps',
  alternativeDistributionPackageVersions: 'apps',
  alternativeDistributionDomains: 'apps',
  alternativeDistributionKeys: 'apps',
  analyticsReportRequests: 'analytics',

  // Version lifecycle and submission
  appStoreVersions: 'versions',
  appStoreVersionLocalizations: 'versions',
  appStoreVersionSubmissions: 'versions',
  appStoreVersionReleaseRequests: 'versions',
  appStoreVersionPhasedReleases: 'versions',
  appStoreVersionExperiments: 'versions',
  appStoreVersionExperimentTreatments: 'versions',
  appStoreVersionExperimentTreatmentLocalizations: 'versions',
  appStoreReviewDetails: 'versions',
  appStoreReviewAttachments: 'versions',
  reviewSubmissions: 'versions',
  reviewSubmissionItems: 'versions',
  appClipDefaultExperiences: 'versions',
  appClipDefaultExperienceLocalizations: 'versions',
  appClipAdvancedExperiences: 'versions',
  appClipAdvancedExperienceImages: 'versions',
  appClips: 'versions',
  appClipHeaderImages: 'versions',

  // Builds
  builds: 'builds',
  buildBundles: 'builds',
  buildBundleFileSizes: 'builds',
  buildIcons: 'builds',
  buildBetaDetails: 'builds',
  preReleaseVersions: 'builds',
  appStoreVersionBuildLocalizations: 'builds',

  // TestFlight
  betaGroups: 'testflight',
  betaTesters: 'testflight',
  betaTesterInvitations: 'testflight',
  betaAppLocalizations: 'testflight',
  betaBuildLocalizations: 'testflight',
  betaAppReviewDetails: 'testflight',
  betaAppReviewSubmissions: 'testflight',
  betaBuildUsages: 'testflight',
  betaLicenseAgreements: 'testflight',
  betaFeedbackScreenshotSubmissions: 'testflight',
  betaFeedbackCrashSubmissions: 'testflight',
  betaRecruitmentCriteria: 'testflight',
  betaRecruitmentCriterionOptions: 'testflight',
  betaPublicLinkUsages: 'testflight',

  // Customer reviews
  customerReviews: 'reviews',
  customerReviewResponses: 'reviews',
  appStoreReviewSummarizations: 'reviews',

  // In-app purchases
  inAppPurchases: 'iap',
  inAppPurchasesV2: 'iap',
  inAppPurchaseLocalizations: 'iap',
  inAppPurchasePriceSchedules: 'iap',
  inAppPurchasePrices: 'iap',
  inAppPurchasePricePoints: 'iap',
  inAppPurchaseAvailabilities: 'iap',
  inAppPurchaseAppStoreReviewScreenshots: 'iap',
  inAppPurchaseSubmissions: 'iap',
  inAppPurchaseContents: 'iap',
  inAppPurchaseImages: 'iap',
  inAppPurchaseOfferCodes: 'iap',
  inAppPurchaseOfferCodeOneTimeUseCodes: 'iap',
  inAppPurchaseOfferCodeCustomCodes: 'iap',
  inAppPurchaseOfferCodePrices: 'iap',
  inAppPurchaseVersions: 'iap',
  promotedPurchases: 'iap',
  promotedPurchaseImages: 'iap',

  // Subscriptions
  subscriptions: 'subscriptions',
  subscriptionGroups: 'subscriptions',
  subscriptionGroupLocalizations: 'subscriptions',
  subscriptionLocalizations: 'subscriptions',
  subscriptionPrices: 'subscriptions',
  subscriptionPricePoints: 'subscriptions',
  subscriptionAvailabilities: 'subscriptions',
  subscriptionIntroductoryOffers: 'subscriptions',
  subscriptionPromotionalOffers: 'subscriptions',
  subscriptionPromotionalOfferPrices: 'subscriptions',
  subscriptionOfferCodes: 'subscriptions',
  subscriptionOfferCodeOneTimeUseCodes: 'subscriptions',
  subscriptionOfferCodeCustomCodes: 'subscriptions',
  subscriptionOfferCodePrices: 'subscriptions',
  subscriptionAppStoreReviewScreenshots: 'subscriptions',
  subscriptionSubmissions: 'subscriptions',
  subscriptionImages: 'subscriptions',
  subscriptionVersions: 'subscriptions',
  winBackOffers: 'subscriptions',
  winBackOfferPrices: 'subscriptions',
  subscriptionGracePeriods: 'subscriptions',

  // Pricing
  appPriceSchedules: 'pricing',
  appPricePoints: 'pricing',
  appPrices: 'pricing',

  // Store presence and marketing
  appScreenshotSets: 'marketing',
  appScreenshots: 'marketing',
  appPreviewSets: 'marketing',
  appPreviews: 'marketing',
  appCustomProductPages: 'marketing',
  appCustomProductPageVersions: 'marketing',
  appCustomProductPageLocalizations: 'marketing',
  appEvents: 'marketing',
  appEventLocalizations: 'marketing',
  appEventScreenshots: 'marketing',
  appEventVideoClips: 'marketing',

  // Provisioning
  bundleIds: 'provisioning',
  bundleIdCapabilities: 'provisioning',
  certificates: 'provisioning',
  devices: 'provisioning',
  profiles: 'provisioning',
  merchantIds: 'provisioning',
  passTypeIds: 'provisioning',

  // Users and access
  users: 'users',
  userInvitations: 'users',
  actors: 'users',

  // Xcode Cloud
  ciProducts: 'xcode_cloud',
  ciWorkflows: 'xcode_cloud',
  ciBuildRuns: 'xcode_cloud',
  ciBuildActions: 'xcode_cloud',
  ciArtifacts: 'xcode_cloud',
  ciIssues: 'xcode_cloud',
  ciTestResults: 'xcode_cloud',
  ciMacOsVersions: 'xcode_cloud',
  ciXcodeVersions: 'xcode_cloud',
  scmProviders: 'xcode_cloud',
  scmRepositories: 'xcode_cloud',
  scmGitReferences: 'xcode_cloud',
  scmPullRequests: 'xcode_cloud',

  // Game Center
  gameCenterDetails: 'game_center',
  gameCenterGroups: 'game_center',
  gameCenterAchievements: 'game_center',
  gameCenterAchievementLocalizations: 'game_center',
  gameCenterAchievementImages: 'game_center',
  gameCenterAchievementReleases: 'game_center',
  gameCenterLeaderboards: 'game_center',
  gameCenterLeaderboardLocalizations: 'game_center',
  gameCenterLeaderboardImages: 'game_center',
  gameCenterLeaderboardReleases: 'game_center',
  gameCenterLeaderboardSets: 'game_center',
  gameCenterLeaderboardSetLocalizations: 'game_center',
  gameCenterLeaderboardSetImages: 'game_center',
  gameCenterLeaderboardSetReleases: 'game_center',
  gameCenterLeaderboardSetMemberLocalizations: 'game_center',
  gameCenterAppVersions: 'game_center',
  gameCenterGroupActivities: 'game_center',
  gameCenterActivities: 'game_center',
  gameCenterActivityVersions: 'game_center',
  gameCenterActivityLocalizations: 'game_center',
  gameCenterActivityImages: 'game_center',
  gameCenterChallenges: 'game_center',
  gameCenterChallengeVersions: 'game_center',
  gameCenterChallengeLocalizations: 'game_center',
  gameCenterChallengeImages: 'game_center',
  gameCenterMatchmakingQueues: 'game_center',
  gameCenterMatchmakingRuleSets: 'game_center',
  gameCenterMatchmakingRules: 'game_center',
  gameCenterMatchmakingTeams: 'game_center',
  gameCenterMatchmakingRuleSetTests: 'game_center',
  gameCenterMatchmakingBooleanRuleResults: 'game_center',
  gameCenterMatchmakingNumberRuleResults: 'game_center',
  gameCenterMatchmakingTeamAssignments: 'game_center',
  gameCenterEnabledVersions: 'game_center',
  gameCenterPlayerAchievementSubmissions: 'game_center',
  gameCenterChallengeVersionReleases: 'game_center',
  gameCenterActivityVersionReleases: 'game_center',
  achievements: 'game_center',
  leaderboards: 'game_center',
  leaderboardSets: 'game_center',

  // Analytics, sales and finance
  salesReports: 'analytics',
  financeReports: 'analytics',
  analyticsReports: 'analytics',
  analyticsReportSegments: 'analytics',
  analyticsReportInstances: 'analytics',
  perfPowerMetrics: 'analytics',
  diagnosticSignatures: 'analytics',
  diagnosticLogs: 'analytics',
  metrics: 'analytics',

  // Webhooks and notifications
  webhooks: 'webhooks',
  webhookDeliveries: 'webhooks',
  webhookEvents: 'webhooks',

  // Sandbox
  sandboxTesters: 'sandbox',
  sandboxTestersV2: 'sandbox',

  // Nominations and custom pages
  nominations: 'marketing',

  // Background assets
  backgroundAssets: 'background_assets',
  backgroundAssetVersions: 'background_assets',
  backgroundAssetUploadFiles: 'background_assets',
  backgroundAssetsV2: 'background_assets',
  appStoreVersionBackgroundAssets: 'background_assets',
  backgroundAssetVersionInternalBetaReleases: 'background_assets',
  backgroundAssetVersionSubmissions: 'background_assets',
  androidToIosAppMappingDetails: 'apps',
  appTags: 'apps',
  endAppAvailabilityPreOrders: 'apps',
  appStoreVersionPromotions: 'versions',
  appClipAppStoreReviewDetails: 'versions',
  routingAppCoverages: 'versions',
  betaAppClipInvocations: 'testflight',
  betaAppClipInvocationLocalizations: 'testflight',
  betaCrashLogs: 'testflight',
  buildBetaNotifications: 'testflight',
  buildUploads: 'builds',
  buildUploadFiles: 'builds',
  subscriptionGroupSubmissions: 'subscriptions',
  subscriptionGroupVersions: 'subscriptions',
  subscriptionPlanAvailabilities: 'subscriptions',
  gameCenterAchievementVersions: 'game_center',
  gameCenterLeaderboardVersions: 'game_center',
  gameCenterLeaderboardSetVersions: 'game_center',
  gameCenterLeaderboardEntrySubmissions: 'game_center',
  marketplaceWebhooks: 'webhooks',
  webhookPings: 'webhooks',
  sandboxTestersClearPurchaseHistoryRequest: 'sandbox',
  backgroundAssetVersionAppStoreReleases: 'background_assets',
  backgroundAssetVersionExternalBetaReleases: 'background_assets',
}

/** Human-readable blurb for each domain, used in docs and the discovery tool. */
export const DOMAIN_DESCRIPTIONS: Record<string, string> = {
  apps: 'Apps, metadata, localizations, categories, availability, encryption declarations',
  versions: 'App Store version lifecycle, submissions, phased release, A/B experiments',
  builds: 'Builds, build bundles, icons, pre-release versions',
  testflight: 'TestFlight beta groups, testers, feedback, crash submissions',
  reviews: 'Customer reviews and developer responses',
  iap: 'In-app purchases, pricing, offer codes, promoted purchases',
  subscriptions: 'Subscriptions, groups, offers, win-back, offer codes',
  pricing: 'App price schedules and price points',
  marketing: 'Screenshots, previews, custom product pages, in-app events',
  provisioning: 'Bundle IDs, certificates, devices, profiles, capabilities',
  users: 'Team members, invitations, roles',
  xcode_cloud: 'Xcode Cloud products, workflows, build runs, artifacts, SCM',
  game_center: 'Game Center achievements, leaderboards, matchmaking, challenges',
  analytics: 'Sales and finance reports, analytics reports, performance metrics',
  webhooks: 'Webhook configuration and delivery diagnostics',
  sandbox: 'Sandbox testers',
  background_assets: 'Background assets and asset packs',
  storekit: 'App Store Server API (StoreKit 2): transactions, subscription status, refunds',
  meta: 'Server introspection: auth status, rate limits, domain discovery',
  misc: 'Endpoints not yet assigned to a domain',
};

export function domainFor(root: string): string {
  return DOMAIN_MAP[root] ?? 'misc';
}
